# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - S22-Team01-Nguyen-Milford-Garcia-Mccoy-Faulk-Howes_new/front-end
    exclude:
      - S22-Team01-Nguyen-Milford-Garcia-Mccoy-Faulk-Howes_new/Sprint1_research
    

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  workingDirectory: 'S22-Team01-Nguyen-Milford-Garcia-Mccoy-Faulk-Howes_new/front-end'
  displayName: 'npm install and build'
