SELECT * FROM DRIVER;
SELECT * FROM SPONSORORG;
SELECT * FROM CARTITEM;
SELECT * FROM ORDERS;
SELECT * FROM ITEM;
INSERT INTO CARTITEM(ItemID, ItemName, Price, Quantity, UID, SID) VALUES(1,"Testitem1",50,1,1,1);
INSERT INTO CARTITEM(ItemID, ItemName, Price, Quantity, UID, SID) VALUES(2,"Testitem2",200,3,1,1);
INSERT INTO CARTITEM(ItemID, ItemName, Price, Quantity, UID, SID) VALUES(3,"Testitem3",600,2,1,1);

