USE CPSC4910;
SELECT First_name,Last_name,Email,Address,Phone_number FROM DRIVER INNER JOIN SPONSORANDDRIVER ON SPONSORANDDRIVER.UID = DRIVER.UID WHERE SID = 1;
SELECT * FROM DRIVER;
SELECT * FROM SPONSORORG;
INSERT INTO SPONSORANDDRIVER(UID,SID) VALUES(1,1)
DELETE FROM SPONSORANDDRIVER WHERE UID = 1 AND SID = 1;