-- Point update
DELIMITER $$
CREATE TRIGGER POINTUPDATE
AFTER UPDATE
ON POINTBALANCE FOR EACH ROW
BEGIN
	IF OLD.Amount <> NEW.Amount THEN
		INSERT INTO POINTBALANCELOG(Point_Update, Update_Status, PointDate, PointID, SUID)
        VALUES(NEW.Amount, CONCAT('Change from ',OLD.Amount), CURRENT_TIMESTAMP(), OLD.PointID, OLD.SUID);
	END IF;
END$$
DELIMITER ;

-- Password Change
DELIMITER $$
CREATE TRIGGER PASSCHANGEDRIVER
AFTER UPDATE
ON DRIVER FOR EACH ROW
BEGIN
	IF OLD.Password_hash <> NEW.Password_hash THEN
		INSERT INTO PASSWORDCHANGES(User_type, Pwd_date, Change_type)
        VALUES(OLD.Email, CURRENT_TIMESTAMP(), OLD.Password_hash);
	END IF;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER PASSCHANGESPONSORACCT
AFTER UPDATE
ON SPONSORACCT FOR EACH ROW
BEGIN
	IF OLD.Password_hash <> NEW.Password_hash THEN
		INSERT INTO PASSWORDCHANGES(User_type, Pwd_date, Change_type)
        VALUES(OLD.Email, CURRENT_TIMESTAMP(), OLD.Password_hash);
	END IF;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER PASSCHANGEADMIN
AFTER UPDATE
ON ADMIN FOR EACH ROW
BEGIN
	IF OLD.Password_hash <> NEW.Password_hash THEN
		INSERT INTO PASSWORDCHANGES(User_type, Pwd_date, Change_type)
        VALUES(OLD.Email, CURRENT_TIMESTAMP(), OLD.Password_hash);
	END IF;
END$$
DELIMITER ;

-- Driver login attempt
INSERT INTO LOGINATTEMPTS(Login_date, Username, Status) VALUES(CURRENT_TIMESTAMP(), DRIVER.Email, '');

-- Update Applications
UPDATE APPLICATION
SET Appstatus = '' AND Reason = ''
WHERE UID = '' AND SID = '';
